(add-to-list 'default-frame-alist
             '(font . "Source Code Pro-14"))
;;(setq initial-frame-alist (quote ((fullscreen . maximized))))
;;(add-to-list 'default-frame-alist '(fullscreen . maximized))
(scroll-bar-mode -1)
(tool-bar-mode -1)
(menu-bar-mode -1)
(setq inhibit-splash-screen t)
;; (global-hl-line-mode t)
(provide 'init-ui)
